### ISSUE TITLE
npm run load error

### ISSUE THREAD

**Issue by wangxin1999** [wuomzfx/pdfGPT#1]
Warning: Bad value, for key "Trapped", in Info: false.
node:fs:601
  handleErrorFromBinding(ctx);
  ^

Error: ENOENT: no such file or directory, open './pdfGPT-main/cache/files/e_2018_summary.json'
在运行这个代码的时候出现了如下的错误，想问您这个如何解决

**Comment by wangxin1999** [comment]
已经解决，需要自己创建files文件，感谢您的这个项目

**Comment by yenava** [comment]
load一直超时
node:internal/process/promises:289
            triggerUncaughtException(err, true /* fromPromise */);
            ^

<ref *1> Error: connect ETIMEDOUT 162.125.2.5:443

**Comment by wuomzfx** [comment]
挂梯子了吗？国内ban了

**Comment by yenava** [comment]
挂了，全局代理也不行，和节点有关吗？
